#!/bin/bash

echo "update elasticsearch host {new_ip}"

if [ $# -eq 0 ] || [ $# -gt 1 ]; then
 echo "Please only input a new IP, ex: 192.168.1.1"
 exit
fi

if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invaild IP formate"
  exit
fi

echo "set global variable ES_HOSTS_IP to $1"
sed -i '/ES_HOSTS_IP=/s/=.*/='$1':9200/' .env
