#!/bin/bash

echo "upctl {old_ip} {new_ip}"
echo "upctl {new_ip}"
echo "upctl -e {new_ip} # -e means change elasticSearch host IP address"


while getopts 'e:' OPT; do
    case $OPT in
        e) ES_ARG="$OPTARG";;
    esac
done

if  [[ ! -z $ES_ARG ]] ; then
  echo "set global variable ES_HOSTS_IP to $ES_ARG"
  sed -i -e '/ES_HOSTS_IP=/s/=.*/='$ES_ARG':9200/' .env
  exit
fi

if [ $# -eq 0 ] || [ $# -gt 2 ]; then
 echo "Please only input old and new IP or new IP"
fi

if [ $# -eq 2 ]; then
 ACTION="replace"
 echo $1 $2
fi

if [ $# -eq 1 ]; then
 ACTION="new"
 echo $1
fi

host_name=$(hostname -f)

if [ "$ACTION" = "new" ]; then
 if [[ $(cat /etc/os-release|grep ^NAME) == *"CentOS"* ]]; then
  ifacename=$(ip addr show | awk '/'$1'/ {print $NF}')
 else
  ifacename=$(ip addr show | grep -w $1 | cut -d " " -f 11)
 fi
 if [ "$ifacename" == "" ]; then
  echo "no interface with this new IP"
  exit
 fi
 if [ $# -eq 2 ]; then
  ACTION="replace"
 fi
echo "Interface is $ifacename"
echo "replace HOST_IFACE by $ifacename"
sed -i 's/HOST_IFACE/'"$ifacename"'/g' conf/mars/mars_collectd.conf

echo "repplace HOST_IP_TO_ONOS_IP by $1"
echo "replace conf/mars/mars_collectd.conf"
sed -i 's/HOST_IP_TO_ONOS_IP/'"$1"'/g' conf/mars/mars_collectd.conf
echo "replace conf/elasticsearch/elasticsearch.yml"
sed -i 's/HOST_IP_TO_ONOS_IP/'"$1"'/g' conf/elasticsearch/elasticsearch.yml
sed -i 's/HOST_NAME/'"$host_name"'/g'  conf/elasticsearch/elasticsearch.yml
echo "replace docker-compose.yml"
sed -i 's/HOST_IP_TO_ONOS_IP/'"$1"'/g' docker-compose.yml
echo "replace conf/kibana/kibana.yml"
sed -i 's/HOST_IP_TO_ONOS_IP/'"$1"'/g' conf/kibana/kibana.yml
fi

if [ "$ACTION" = "replace" ]; then
 if [[ $(cat /etc/os-release|grep ^NAME) == *"CentOS"* ]]; then
  nifacename=$(ip addr show | awk '/'$2'/ {print $NF}')
 else
  nifacename=$(ip addr show | grep -w $2 | cut -d " " -f 11)
 fi
 if [ "$nifacename" = "" ]; then
  echo "no interface with this IP"
  exit
 fi

 if [[ $(cat /etc/os-release|grep ^NAME) == *"CentOS"* ]]; then
  oifacename=$(ip addr show | awk '/'$1'/ {print $NF}')
 else
  oifacename=$(ip addr show | grep $1 | cut -d " " -f 11)
 fi
 if [ "$oifacename" = "" ]; then
  echo "Interface is $ifacename"
  echo "don't replace $ifacename"
 else
  sed -i 's/'"$oifacename"'/'"$nifacename"'/g' conf/mars/mars_collectd.conf
 fi

echo "repplace $1 by $2"
echo "replace conf/mars/mars_collectd.conf"
sed -i 's/'"$1"'/'"$2"'/g' conf/mars/mars_collectd.conf
echo "replace conf/elasticsearch/elasticsearch.yml"
sed -i 's/'"$1"'/'"$2"'/g' conf/elasticsearch/elasticsearch.yml
echo "replace docker-compose.yml"
sed -i 's/'"$1"'/'"$2"'/g' docker-compose.yml
echo "replace conf/kibana/kibana.yml"
sed -i 's/'"$1"'/'"$2"'/g' conf/kibana/kibana.yml

fi

if [ "$ACTION" == "" ]; then
  echo "Do nothing"
fi
