---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-2
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-1
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "nodea"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mars-download
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-2
  local:
    path: /mnt/disks/ssd2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "nodea"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: es-data-claim
# namespace: accton-mars
# spec:
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 4Gi
#   storageClassName: local-storage
