---
apiVersion: v1
kind: Service
metadata:
  name: mars-web
  namespace: nocsys-mars
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mars-nginx
  ports:
    - port: 443
      nodePort: 30443
      name: https
    - port: 69
      name: tftp

---
apiVersion: v1
kind: Service
metadata:
  name: mars
  namespace: nocsys-mars
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mars
  ports:
    - port: 8181
      name: mars
    - port: 8443
      name: webssh
    - port: 3233
      name: websocket

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: nocsys-mars
spec:
  selector:
    app.kubernetes.io/name: mars-elasticsearch
  ports:
    - name: rest
      port: 9200
    - name: inter-node
      port: 9300

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: nocsys-mars
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: mars-logstash
  ports:
    - protocol: TCP
      port: 5514
      name: syslog-tcp
    - protocol: UDP
      port: 5514
      name: syslog-udp
      nodePort: 32514
    - protocol: TCP
      port: 5044
      name: beats  
    - protocol: UDP
      port: 25826
      name: collectd
    - port: 3233
      name: websocket
