---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: accton-mars
  name: mars-configmap
data:
  mars_env_topology: "clos"
  mars_env_java_ops: "-Xms8G -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode \
                      -Dcom.sun.management.jmxremote -Dds.lock.timeout.milliseconds=10000"
  mars_env_onos_app: >
    drivers
    com.accton.drivers.accton.gnmi
    com.accton.drivers.accton.rest
    com.accton.drivers.accton.snmp
    proxyarp
    restsb
    snmp
    org.onosproject.drivers.h3c.netconf
    linkdiscovery
    com.accton.provider.switchpolling
    com.accton.eventclient
    com.accton.useraccount
    com.accton.defaultcfg
    com.accton.alert
    com.accton.analyzer
    com.accton.utility
    com.accton.healthycheck
    com.accton.dhcpserver
    com.accton.dhcpv6server
    com.accton.endpoint
    com.accton.monitor
    com.accton.ntpserver
    com.accton.qos
    com.accton.sflow
    com.accton.storm-control
    com.accton.switchmgmt
    com.accton.topology
    com.accton.websocket
    com.accton.webssh
  logstash_env_java_ops: "-Xmx2g -Xms2g"
  elasticsearch_env_java_ops: "-Xms2g -Xmx2g"
