---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nocsys-mars
  name: mars-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mars-logstash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mars-logstash
    spec:
      containers:
      - name: logstash
        image: 'nocsysmars/logstash:7.5.2-oss'
        imagePullPolicy: IfNotPresent
        env:
        - name: LS_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: mars-configmap
              key: logstash_env_java_ops
        - name: ES_HOSTS
          value: "elasticsearch.nocsys-mars.svc.cluster.local:9200"
