---
apiVersion: v1
kind: Service
metadata:
  name: mars-web
# namespace: nocsys-mars
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mars-nginx
  ports:
    - port: 443
      nodePort: 30443

---
apiVersion: v1
kind: Service
metadata:
  name: mars
# namespace: nocsys-mars
spec:
  selector:
    app.kubernetes.io/name: mars
  ports:
    - port: 8181

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
# namespace: nocsys-mars
spec:
  selector:
    app.kubernetes.io/name: mars-elasticsearch
  clusterIP: None
  ports:
    - name: rest
      port: 9200
    - name: inter-node
      port: 9300