---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
# namespace: nocsys-mars
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mars-elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mars-elasticsearch
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: elasticsearch
        image: 'nocsysmars/elasticsearch:7.9.0-oss'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - name: inter-node
          containerPort: 9300
          protocol: TCP
        volumeMounts:
        - name: es-data-claim
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: cluster.name
          value: mars-elk
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.initial_master_nodes
          valueFrom:
            fieldRef:
              fieldPath: metadata.name    
        - name: discovery.zen.ping.unicast.hosts
          value: "es-cluster-0.elasticsearch"
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: mars-configmap
              key: elasticsearch_env_java_ops
        - name: network.host
          value: "0.0.0.0"
      initContainers:
      - name: fix-permissions
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: es-data-claim
            mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image:  busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image:  busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      # volumes:
      # - name: elasticsearch-data
      #   persistentVolumeClaim:
      #     claimName: es-data-claim
  volumeClaimTemplates:
  - metadata:
      name: es-data-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 4Gi
