- name: ""
  hosts: localhost 
  vars:
   - path: "{{path}}"
  tasks: 
   - name: "import keepalive"
     shell: docker load -i {{ path }}/docker_tar/keepalived_2.0.1.tar
   - name: "import elasticsearch"
     shell: docker load -i {{ path }}/docker_tar/elasticsearch_6.1.0.tar
   - name: "import logstash"
     shell: docker load -i {{ path }}/docker_tar/logstash_6.1.0.tar
   - name: "import nginx"
     shell: docker load -i {{ path }}/docker_tar/nginx_1.14.0.tar
   - name: "import mars"
     shell: docker load -i {{ path }}/docker_tar/mars_master.tar
   - name: "create /opt/accton if the dir is not exist"
     file:
       path: /opt/accton
       state: directory
       mode: 0755
   - name: "start docker containers"
     shell: docker-compose -f {{ path }}/docker-compose.yml up -d
